### ISSUE TITLE
HashBang Fails to Build on Mono < version 3.2.4

### ISSUE THREAD

**Issue by scitesy** [ZachBray/HashBang#2]
Line 140 of src/TypeInferred.HashBang.Core/Website.fs reads:

```
if metadata.CanCacheResponse then Some CompressionLevel.Optimal
```

Although this line is correct. Any Mono version below 3.2.4 has a System.IO.Compression.CompressionLevel enum of CompressionLevel.Optional instead of CompressionLevel.Optimal. This is fixed in Mono 3.2.4. The workaround for lower Mono versions is to change line 140 to:

```
if metadata.CanCacheResponse then Some CompressionLevel.Optional
```

**Comment by ZachBray** [comment]
See Issue #2.

**Comment by scitesy** [comment]
I'll see what I can do with pound if statements to determine behavior.

**Comment by scitesy** [comment]
Successfully tested.
