### ISSUE TITLE
CrawlerFriendlyDynamicWebsite on Mono Fails at Runtime

### ISSUE THREAD

**Issue by scitesy** [ZachBray/HashBang#3]
Line 84 of src/TypeInferred.HashBang.Core/Website.fs reads:

```
use compressor = new GZipStream(memoryStream, level, false)
```

In Mono this .NET 4.5 constructor signature throws a NotImplementedException. It has a MonoTODO attribute in the Mono source code at:

   https://github.com/mono/mono/blob/master/mcs/class/System/System.IO.Compression/GZipStream.cs

My current work around is to change this line to the following implemented constructor signature:

```
use compressor = new GZipStream(memoryStream, CompressionMode.Compress, false)
```

This allows the demo to run however at this time, I am uncertain about the implications of the workaround.

**Comment by ZachBray** [comment]
How about trying something from [DotNetZip](http://dotnetzip.codeplex.com/)? Otherwise, maybe we should just add some `#if MONO` directives or a cached check for `assembly.GetType("Mono.Runtime")` to determine behaviour.

**Comment by ZachBray** [comment]
Oh and thanks for spotting this!

**Comment by ZachBray** [comment]
I've updated the code (and pushed out a new NuGet package) with DotNetZip's GZipStream now. Haven't tested it under mono yet. Hopefully it will work!

**Comment by scitesy** [comment]
I'll test it today. Thank you! Would this be a temporary fix till Mono implements the GZipStream constructor or permanent?

**Comment by ZachBray** [comment]
I think it will be permanent. It is meant to be more reliable than the built in `GZipStream`, which sometimes increases the size of the payload. Thanks for trying it out. Let me know how it goes!

Oh, I think there may be a broken link to an "app.css" that doesn't exist in one of the samples. If you run into this, just remove it and all references to it.

**Comment by scitesy** [comment]
Successfully tested. The Sample fsproj needs updated with the three new dependencies. You nicely killed two bugs with one set of changes. Thanks! I love FunScript and HashBang. They are going to be a great combination-like peanut butter and jelly.

**Comment by ZachBray** [comment]
Really glad you like it! I'm working with it for a side-project at the moment, which is helping to guide the requirements. After that, I'll try to get some samples together on a website like FunScript.
